### PR TITLE
Arm builds

### PR DESCRIPTION
**Pull request by bcomnes**
This PR enables arm targets for linux builds and also enables windows builds on travis, and adds a no-op to appveyor for testing.

### CODE REVIEW

**Comment by cfry** [comment]
fantastic!
So is the linux build now like the windows build in that
it carries in its one file the code for
"normal" linux as well as the ARM-linux needed by Dexter?
As such "installing" it on the linux does the right thing
depending on sensing the hardware?

**Comment by bcomnes** [comment]
@cfry I'm not 100% sure yet, still investigating the build artifacts.

**Comment by bcomnes** [comment]
Looks like travis's windows environment isn't quite ready for primetime yet.

**Comment by bcomnes** [comment]
Ok @cfry, linux AppImage builds are published for individual architects rather than a mega-installer.  I don't see an option for an AppImage with all architectures in a single installer.

**Comment by bcomnes** [comment]
Ok @cfry, this looks good to merge.  I have no idea if the arm builds work on our target boards, but give it a shot.

**Comment by cfry** [comment]
Excellent.
I *think* you have a Dexter processor board,
but I don't know how to get code on and off of it.
If you can figure this out and are brave,
the initial test would be:
- Launch, see if the window comes up,
and no errors in the Dev tools console.
- Choose menu item:
Test/Run all tests.
this takes several minutes, pops up several windows,
like for a video camera feed, getting pages, etc.
Not easy for me to describe which are correct,
but they are part of the "visual tests" for human evaluation.
Running the testsuite also prints out a lengthy report
in the output pane.
Errors are printed in RED.
The very bottom of the report will print total number of errors.
There's always 2 errors in the very beginning
that are there just to test that the test suite itself
is correctly displaying errors.
These 2 errors are omitted from the final total.
There is always (now) one error in the total
on speech reco not working.
But I'd expect more errors on this new build.
Just copy and send me the full report if you
make it that far.
Otherwise I'll ask James N about doing this,
or helping me do it.

James N has been investigating app-get
to get new software onto Dexter as of late.
Perhaps this is appropriate for a new DDE???

**Comment by bcomnes** [comment]
Unfortunately I didn't have the bandwidth to work on the websocket project, and I was asked to send back the dexter boards so I no longer have one to test with.

**Comment by bcomnes** [comment]
Do you want to merge this? Or continue without arm builds?  It sounds like maybe this isn't exactly what we were looking for.

**Comment by JamesNewton** [comment]
I personally don't see a need for Arm builds... unless someone wants to try
running DDE on a low end platform? I think there was interest in having a
tablet with Dexter. Would this build install on an Android?

James Newton
MassMind.org <http://www.massmind.org/>
1-970-462-7764

**Comment by bcomnes** [comment]
> Would this build install on an Android? 

I don't think so, although you CAN get node processes to run on android.  You typically need to either root the phone or wrap it in the android app packaging framework.  Phonegap comes to mind.

**Comment by cfry** [comment]
The real barrier here is that Electron can't run on Android or iOS.
I just checked the web and didn't see any hint of a change on this front.

We could probably get the job engine to run in a node environment
on Android, but I don't see the point in doing that, as it would
have roughly no UI.

We do have the MS Surface tablet solution (which runs windows).

I'm hopeful that *someone* will make Electron run on android some day.
If we get big screens on an Android computer, then that
will make a lot more sense than a tiny phone screen
for the complex UI of DDE.

**Pull request merged**
