### PR TITLE
Update windows target to include 32 bit builds

### PR DESCRIPTION
**Pull request by bcomnes**
Re our email, I think this would be the proper config for a 32 + 64 bit build on windows.  I haven't validated it yet, so lets make sure it builds before we merge.

### CODE REVIEW

**Comment by bcomnes** [comment]
Great! Looks like that worked :)

screen shot 2019-02-21 at 8 20 44 am

**Comment by cfry** [comment]
Wow, that was speedy work!
I did get one "failed" email from AppVeyor but then
another one saying it worked so I guess that was due to your
Json fix.

"Looks like when you build 32 or 64 bit images, you get one installer for
both.  Great!"
Yes that is great because I was thinking last night that a downside of
adding
another platform is that users would have to figure out what kind of
windows machine they had,
get it wrong and screw up so automating this so the user chooses one
download
and it just installs the right thing gets rid of a lot of support calls!
_____

"it looks like Travis now supports windows too, so we could move the window
build over to the service we do our Mac, and linux builds.  It would
eliminate some moving parts.  Let me know if you would like me to make that
change, it would not take long, less than an hour."
At least at first blush this sounds like a great idea.
Simplifying in this area is very appealing.
I suppose some day Appveyor might support all our platforms,
in which case we'd have the option to switch them all back.
Having multiple paths is good, but multiple PARTIAL paths
is just a headache.
I'd say if you think this is a good idea, go ahead and do it!
_____
In this neighborhood,
can we get a build for Dexter's processor?
James Newton got DDE installed on his Dexter processor by
issuing some magic commands you sent for install,
but can that be translated into just another build that
a user could pick from Github releases page and install?

**Comment by bcomnes** [comment]
If electron builder supports the right arm architecture we could do that. Want me to look into that for you?

**Comment by cfry** [comment]
Please!

**Comment by bcomnes** [comment]
Okay, will do.  Taking a few days off here, but I can try to take a look Sunday or Monday.

**Review by cfry — APPROVED** [review]

**Comment by cfry** [comment]
Causes the build process to make one .exe that can be installed on either win 32 or win 64 computers.

**Pull request merged**
