### PR TITLE
Update electron builder

### PR DESCRIPTION
**Pull request by bcomnes**
Lets see if this builds better

### CODE REVIEW

**Comment by bcomnes** [comment]
Hah, now linux is failing.  What a world

**Comment by cfry** [comment]
First, thanks for you rapid response on this.
I'm now in Mexico.

Not sure we have any Linux users so I'm not so
concerned with this right now, but of course would be good
if it worked.

Sorry I was a bit frazzeled when calling you from
Dallas. It was hard to hear you over the PA system.

I don't have a clear picture about how to proceed
with getting your latest changes and doing a build.
Please tell me the correct sequence of cmds to do.
I remember there was something about
git stash
but I didn't understand why that was necessary,
nor the right sequence.
Most of the voluminous text output by the
cmds we were using is in the same color
as the text I type in, even though there is
some colored font.
If you had to use different colors for anything,
it would be for my typein and computer's output,
but that would have taking someone with some UI sense.

**Comment by bcomnes** [comment]
Unfortunately git isn’t a series of predictable commands.  Depending on the state of your working directory, and the changes that have been committed to the remote ahead of where you are, you may need to manage a merge conflict which has various solutions which offer pros and cons depending on the situation.  

What we did last night:

git fetch
Git stash
Git pull
Git stash pop
Git add -A
Git commit -m ‘a message for the commit’
Git push

What this does is save uncommitted changes in your working directory to the git stash and cleans your working directory of them.  Then we pull down the changes, then we pop the last stash off the stash stack.  This applies those uncommitted changes to the working directory.  This COULD have resulted in a merge conflict, which you would need to resolve. It appears to have auto merged, so we were able to commit cleanly after that.  

The stash tool is kind of a sharp tool.  Its easy to lose track of work because its as simple as typing git stash clear to delete the stash.  It would have been safer to commit your changes first, then merge with the remote, then push the changes back, but the stash operation was a little more straight forward to do over the phone.

I’m going to poke at the build some more this evening to see whats causing the hangups

**Comment by cfry** [comment]
So i just use git pull on my local copy and not fo merge pull tequest on
git website?

**Comment by bcomnes** [comment]
Err no I’m not being clear.  Want to schedule a call to do a refresher course on git?  It’s too difficult to explain without screen sharing.

I’ll attempt anyway. Git pull combines a git fetch and a git merge operation.  Until you merge a change from a pr on your remote, you can’t pull or fetch it directly to your computer.

**Comment by bcomnes** [comment]
Ok, this checks out now.  The newer version of electron-builder started trying to target the Snapcraft build target, which travis doesn't support by default.  Since we don't care about this right now, I specified just AppImage target for linux and that should unhitch the build process for now.

**Comment by bcomnes** [comment]
Ok @cfry this is good to merge.  Let me know if this addresses the failing builds you were running into.   Enjoy your trip!

**Pull request merged**
